[package]
name = "xstore"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
byteorder = "1.4.3"
clap = { version = "3.0.7", features = ["derive"] }
image = "0.23.14"
pem = "1.0.2"
rasn = "0.5.0"
rasn-cms = "0.5.0"
rasn-pkix = "0.5.0"
rsa = "0.5.0"
sha2 = "0.10.1"
x509-parser = "0.12.0"

[patch.crates-io]
rasn = { path = "../rasn" }
rasn-cms = { path = "../rasn/standards/cms" }
rasn-pkix = { path = "../rasn/standards/pkix" }

[dev-dependencies]
der-parser = "6.0.0"
