[workspace]
members = ["apk", "appimage", "msix", "xcli", "xcommon"]

[patch.crates-io]
rasn = { path = "../rasn" }
rasn-cms = { path = "../rasn/standards/cms" }
rasn-pkix = { path = "../rasn/standards/pkix" }
