[workspace]
members = ["apk", "appbundle", "appimage", "msix", "xcli", "xcommon"]

[patch.crates-io]
rasn = { git = "https://github.com/XAMPPRocky/rasn" }
rasn-cms = { git = "https://github.com/XAMPPRocky/rasn" }
rasn-pkix = { git = "https://github.com/XAMPPRocky/rasn" }
