[package]
name = "helloworld"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dependencies]
env_logger = "0.9.0"
nativeshell = { git = "https://github.com/dvc94ch/nativeshell", branch = "cross" }
