[package]
name = "xcli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.0.13", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
xapk = { version = "0.1.0", path = "../apk" }
xappimage = { version = "0.1.0", path = "../appimage" }
xcommon = { version = "0.1.0", path = "../xcommon" }
xmsix = { version = "0.1.0", path = "../msix" }
