[package]
name = "xcli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.0.13", features = ["derive"] }
dunce = "1.0.2"
pubgrub = "0.2.1"
quick-xml = { version = "0.23.0-alpha2", features = ["serialize"] }
rasn = "0.5.0"
rasn-cms = "0.5.0"
rasn-pkix = "0.5.0"
reqwest = { version = "0.11.9", features = ["blocking"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
toml = "0.5.8"
which = "4.2.4"
xapk = { version = "0.1.0", path = "../apk" }
xappimage = { version = "0.1.0", path = "../appimage" }
xcommon = { version = "0.1.0", path = "../xcommon" }
xmsix = { version = "0.1.0", path = "../msix" }

[[bin]]
name = "x"
path = "src/main.rs"
