[package]
name = "appbundle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
apple-codesign = { git = "https://github.com/indygreg/pyoxidizer" }
icns = "0.3.1"
log = "0.4.16"
pkcs8 = "0.7.6"
plist = "1.3.1"
rasn = "0.5.0"
rasn-cms = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
x509-certificate = { git = "https://github.com/indygreg/pyoxidizer" }
xcommon = { version = "0.1.0", path = "../xcommon" }
