[package]
name = "appbundle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
icns = "0.3.1"
plist = "1.3.1"
serde = { version = "1.0.136", features = ["derive"] }
xcommon = { version = "0.1.0", path = "../xcommon" }
