[package]
name = "appbundle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
#apple-codesign = { git = "https://github.com/indygreg/pyoxidizer" }
apple-codesign = { path = "../../pyoxidizer/apple-codesign" }
icns = "0.3.1"
pkcs8 = "0.7.6"
plist = "1.3.1"
rasn = "0.5.0"
rasn-cms = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
slog = "2.7.0"
slog-term = "2.8.1"
#x509-certificate = "0.7.0-pre"
x509-certificate = { path = "../../pyoxidizer/x509-certificate" }
xcommon = { version = "0.1.0", path = "../xcommon" }
