[package]
name = "appbundle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
apple-codesign = "0.10.0"
icns = "0.3.1"
pkcs8 = "0.7.6"
plist = "1.3.1"
rasn = "0.5.0"
rasn-cms = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
x509-certificate = "0.11.0"
xcommon = { version = "0.1.0", path = "../xcommon" }
