[package]
name = "xapk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
byteorder = "1.4.3"
cafebabe = "0.5.0"
quick-xml = { version = "0.22.0", features = ["serialize"] }
rasn = "0.5.0"
rasn-pkix = "0.5.0"
roxmltree = "0.14.1"
rsa = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
sha2 = "0.10.1"
tracing = "0.1.29"
xcommon = { version = "0.1.0", path = "../xcommon" }
zip = "0.5.13"

[dev-dependencies]
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.3.7", features = ["env-filter"] }
