[package]
name = "xcommon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
image = "0.24.0"
pem = "1.0.2"
rasn = "0.5.0"
rasn-pkix = "0.5.0"
rsa = "0.5.0"
sha2 = "0.10.1"
zip = "0.5.13"
