on:
  push:
    branches:
    - master
  pull_request:

name: x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        components: clippy, rustfmt
    - run: cargo fmt --all -- --check
    #- run: cargo clippy --workspace --examples --tests --all-features -- -D warnings

  linux:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update && sudo apt-get install libgtk-3-dev
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        targets: x86_64-unknown-linux-gnu,x86_64-apple-darwin,x86_64-pc-windows-msvc,aarch64-linux-android,aarch64-apple-ios
    - uses: subosito/flutter-action@v1
    - uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - run: cargo install --path xcli
    - run: x build -p helloworld --platform linux --arch x64
    - run: x build -p helloworld --platform macos --arch x64
    - run: x build -p helloworld --platform windows --arch x64
    - run: x build -p helloworld --platform android --arch arm64
    #- run: x build -p helloworld --platform ios --arch arm64
    - run: x build -p helloworld --release
    - run: x build -p helloworld --platform android --arch arm64 --release

  #macos:
  #  runs-on: macos-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - uses: hecrj/setup-rust-action@v1
  #    with:
  #      targets: x86_64-unknown-linux-gnu,x86_64-apple-darwin,x86_64-pc-windows-msvc,aarch64-linux-android,aarch64-apple-ios
    #- uses: subosito/flutter-action@v1
    #- run: cargo install --path xcli
    #- run: x build -p helloworld --platform linux --arch x64
    #- run: x build -p helloworld --platform macos --arch x64
    #- run: x build -p helloworld --platform windows --arch x64
    #- run: x build -p helloworld --platform android --arch arm64
    #- run: x build -p helloworld --platform ios --arch arm64
    #- run: x build -p helloworld --release
    #- run: x build -p helloworld --platform android --arch arm64 --release
    #- run: x build -p helloworld --platform ios --arch arm64 --release

  #windows:
  #  runs-on: windows-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - uses: hecrj/setup-rust-action@v1
  #    with:
  #      targets: x86_64-unknown-linux-gnu,x86_64-apple-darwin,x86_64-pc-windows-msvc,aarch64-linux-android,aarch64-apple-ios
  #  - uses: subosito/flutter-action@v1
  #  - run: cargo install --path xcli
    #- run: x build -p helloworld --platform linux --arch x64
    #- run: x build -p helloworld --platform macos --arch x64
    #- run: x build -p helloworld --platform windows --arch x64
    #- run: x build -p helloworld --platform android --arch arm64
    #- run: x build -p helloworld --platform ios --arch arm64
    #- run: x build -p helloworld --release
    #- run: x build -p helloworld --platform android --arch arm64 --release
